name: Run Python Script to generate daily Odds and Commit CSV

on:
  schedule:
    # 1:00 PM EST
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # We enter this at the home folder. Our files are stored in ExternalAPI/moneyline
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ExternalAPI/moneyline/requirements.txt

    - name: Run Python script
      run: python ExternalAPI/moneyline/cloud_odds.py
      env:
        API_KEY: ${{ secrets.CLOUD_API_KEY }}
    - name: Commit and push CSV file
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add *.csv
        git commit -m "Automated CSV update"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
